### ISSUE TITLE
Add multi-select lists for filters

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#133]
Users should be able to select multiple sleep issues from the list, should they be suffering from multiple issues, so that they don't feel restricted and feel that they are able to search for the most relevant content

- [x] Users can select multiple issues from the dropdown list of (initially sleep) issues they are presented with
- [x] There should be options for 'none of the above' and 'all of the above'

**Comment by ellemindwave** [comment]
Wireframe:

![screen shot 2017-05-16 at 22 45 03](https://cloud.githubusercontent.com/assets/26304634/26129693/3177974a-3a89-11e7-892f-645664080a8e.png)

**Comment by ellemindwave** [comment]
![screen shot 2017-05-17 at 09 47 17](https://cloud.githubusercontent.com/assets/26304634/26145829/d60531bc-3ae5-11e7-8645-8de63d841b4b.png)

**Comment by iteles** [comment]
Agreed in sprint planning session:
+ [ ] Styling of the checkboxes is low priority
+ [ ] Box reveal must [degrade gracefully](https://www.w3.org/wiki/Graceful_degradation_versus_progressive_enhancement)
+ [ ] 'None of the above (add your own)' is static text and should be added as a separate issue

**Comment by iteles** [comment]
@indiamindwave24 @ellemindwave Do we have the latest designs for the filters?

**Comment by ellemindwave** [comment]
@iteles, @indiamindwave24 will be doing them this morning and adding them in here for you 👍

**Comment by indiamindwave24** [comment]
<img width="223" alt="screen shot 2017-05-19 at 11 15 01" src="https://cloud.githubusercontent.com/assets/25007700/26244231/d1186bb8-3c86-11e7-8587-f08a42000b13.png">

<img width="385" alt="screen shot 2017-05-19 at 11 14 01" src="https://cloud.githubusercontent.com/assets/25007700/26244239/da945bd4-3c86-11e7-85f4-42f167891ddc.png">

When there is no javascript, just show all beneath question
<img width="281" alt="screen shot 2017-05-19 at 11 29 29" src="https://cloud.githubusercontent.com/assets/25007700/26244209/bcc549c4-3c86-11e7-9419-202edb0910e3.png">

**Comment by iteles** [comment]
@Danwhy Discussed and agreed with @sarahwelton for the Javascript version:   
+ The 'dropdowns' will be revealed boxes as we have originally intended and would be styled as a separate box as above
<img width="171" alt="screen shot 2017-05-23 at 15 01 21" src="https://cloud.githubusercontent.com/assets/4185328/26357915/c031d3c6-3fc8-11e7-8b95-8868f527812e.png">

+ The boxes may still need scroll bars, but these have two provisos:
  + Agreed we would not spend time on styling the scroll bar and would use the native one for now
  + Important that the scroll box is small enough (3 or 4 options) on mobile that a user can have access to the rest of the screen to scroll (so they don't get stuck scrolling just inside this massive never-ending scroll of options)

**Comment by sarahwelton** [comment]
I just wanted to add some clarification as well with the function of the filters: 

By default "show me everything" is selected. 

When a user then selects another option, "show me everything" must de-select. 

If the user then goes back and selects "show me everything" - all other options (multi-select) must de-select. 

Hope that makes sense.

**Comment by sarahwelton** [comment]
Also - "show me everything" or "all audiences" should not appear on the tags on the pieces of content
