### ISSUE TITLE
Event tracking

### ISSUE THREAD

**Issue by sarahwelton** [LDMW/app#216]
As a service provider, I want to quickly and easily track how users are interacting with the service so that I can know where the pain points lie and can most effectively iterate and improve the service

@ellemindwave @katerobb (and others!) please feel free to add to this list. 

Events to be tracked by Google Analytics:

+ [x] email address submitted
+ [x] feedback submitted 
+ [x] content likes / dislikes
+ [x] content clicked on
+ [x] feedback link clicked on
+ [x] which resources are being shared
+ [x] clicks on get support link

**Comment by iteles** [comment]
@sarahwelton This wasn't in our original sprint scope for this sprint, so I'm moving this down to the bottom of the sprint. To confirm, this should be our next highest priority if we have some time in this sprint, over #238 or #244?

**Comment by sarahwelton** [comment]
Leave it as it is for now - we are looking into this in more detail today.

**Comment by Danwhy** [comment]
This can be previewed at: https://www.googletagmanager.com/set_cookie?uiv2&id=GTM-PF8GGT7&gtm_auth=zlXjygHCnu3TqOP3BWwBsQ&gtm_preview=3&gtm_debug=x&url=https://ldmw-app-staging.herokuapp.com
