### ISSUE TITLE
Migrate from Phoenix to Django

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#483]
Overall high level plan:
- [ ] Consider what rearchitechuring some of the ways we are storing our data in wagtail #486 
- [ ] Copy data to new wagtail instance #487
- [ ] Transfer over templates
- [ ] Set up non static routes in python
  - [ ] Set up google sheets logic in python
  - [ ] Set up search logic in python (consider elastic search)
  - [ ] Storing likes data in our database
  - [ ] Storing all data sent to spreadsheet with python
- [ ] Write python tests
- [ ] Relocate all js and css files
- [ ] Resetup deployment and ci
(we will add to this list as tasks come up)

**Comment by shouston3** [comment]
The above will be implemented as a pull request into this repo to retain all of the previous issues and work that has been added to this repo

**Comment by shouston3** [comment]
Moved to here: https://github.com/LDMW/cms/issues/50

**Comment by nelsonic** [comment]
@shouston3 we still need to capture the _reason_ why we are migrating to _only_ using Wagtail/Django/Python instead of Phoenix/Elixir/Erlang. 
we need to have a _clear_ decision from the _product owner_ for this work `before` starting it 
otherwise it _looks_ like we are just "_making up work_" to keep "_busy_".

**Comment by reddog** [comment]
@nelsonic Wasn't this fully covered during the call on Thursday?  There were a number of relevant comments including your recommendation that based on currently understood project spec (and foreseeable project spec), the Phoenix layer wouldn't add any value to the project and would detract from it (net effect).

**Comment by nelsonic** [comment]
@reddog we _prefer_ to have decisions _precisely recorded_ rather than made _verbally_; much easier to send a link to a stakeholder with supporting detail for a decision than to attempt to re-count a telephone conversation. 👍

**Comment by reddog** [comment]
@nelsonic Thanks for adding that clarity. To help us get to closely recording the advice you gave, would you be able to summarise that and then the product owner could confirm or otherwise? Our listing down your comments would already be second hand.

**Comment by Cleop** [comment]
I think it would be best if @ellemindwave, as the product owner, first explains why the proposed change in technology was put forward by the MV team. Then @nelsonic can fill in any gaps with his technical perspective as he did when we discussed the proposal on the call.

**Comment by reddog** [comment]
@Cleop From my recollection of the group meeting, I don't think that the MV team did propose the change in technology.  A query was raised to understand better why the current technology architecture is in place and if that is the best way to continue.  @nelsonic then replied from a technical architecture perspective - I think that's what we're waiting for a summary of.

**Comment by nelsonic** [comment]
@reddog  there appears to be a misunderstanding / misinterpretation somewhere ... 😕 

My "advice" is to _listen_ to the Product Owner who _rightly_ pointed out 
that serving CMS pages through Phoenix adds an _unnecessary_ step 
to content publishing/updating which is using developer time in-effectively. 

> I _agreed_ with @sarahwelton that we don't _want_ to have a "bespoke" CMS solution 
that ends up requiring a "_specialised_" team of developers to maintain/update/extend it.

The _last_ thing we (@dwyl) want is our clients/projects being _dependent_ on us, 
we want to make the code as accessible/beginner-friendly as possible (_so that **any** team of developers can maintain/extend it_) while ensuring that it is _robust and reliable_. 

When I _proposed_ the initial architecture, please see:
https://github.com/LDMW/app/tree/e0c6d43d306071e82afdcec0682d07e49b29e5c6#project-overview
_**notice** how my original diagram shows the **content** being **served** from **Wagtail**_ (_through CloudFlare for speed_) ?
The idea was to build the "**peer-to-peer**" elements of user interaction in Phoenix, 
_not_ to serve the CMS content through Phoenix ... 

The _requirement_ was for "**peer-to-peer**" user interaction, i.e. users (_suffering with sleep-related mental health issues_) would be able to interact with and help _each_ other with some moderation but with the aim of helping each other find ways to overcome their sleep issues.

> Our idea was to have "Chat" functionality in the LDMW Web app which would allow users to communicate in real-time. _However_ this was _not_ meant to be built during the "Alpha" phase, rather it was to be _re-visited_ in "Beta". 
> Phoenix is _brilliant_ for peer-to-peer. It uses the Erlang VM which is what WhatsApp, WeChat and Facebook Messenger all use for low-latency, high reliability chat.

In light of the _change in requirements_ (_away from having a "**peer-to-peer**" application_) -
 which Kumar _confirmed_ on the call -  I ***agreed*** with Sarah that Phoenix is not required for running a CMS. The conclusion from the call is that LDMW is going to be a "_service_" which then directs users to other services, e.g: https://www.bigwhitewall.com

> My **_exact_ words** were: "It breaks my heart, but if we only need a CMS then we should consider removing Phoenix". (_i.e. if we don't want peer-to-peer anymore then we probably don't need Phoenix_)

I _followed_ up with a **question**: What will _differentiate_ LDMW from other Content-based Websites?  

> _Why_ &/or _How_ would someone visit LDMW's website in the first place? 
is the content going to be _better_ (_more relevant to the target audience_) 
than any of the _existing_ content on the web? e.g:
> + Sleep Foundation https://sleepfoundation.org/insomnia/content/what-causes-insomnia
> + WebMD: http://www.webmd.com/sleep-disorders/guide/insomnia-symptoms-and-causes
> + Help Guide: https://www.helpguide.org/articles/sleep/insomnia-causes-and-cures.htm

> What is the **USP** that will give people a _reason_ to visit LDMW over another website/service? 
(_I thought "peer-to-peer" was the USP..._)

If we use an _existing_ CMS and simply add content, how long will it take to have _enough original_ content to start _ranking_ for the specific keywords in order to get organic traffic to the site?

To be clear, I'm not _against_ removing Phoenix (_especially if it's causing a "bottleneck" in content creation/publishing; that was **never** the intention_)
I just want it to be _recorded_ that it's not _my_ decision to remove Phoenix; 
I _still_ think that the original idea of having "**peer-to-peer**" mental health support is a "great feature" and for that Phoenix is _perfect_! (_nobody builds chat in Python/Django, it would be like digging a swimming pool with a teaspoon..._) 
I merely provided a "_high-level estimate_" for how long it would take to remove Phoenix from the _current_ LDMW setup,  and asked for the _decision_ to be recorded in an issue.

**Comment by nelsonic** [comment]
@reddog  there appears to be a misunderstanding / misinterpretation somewhere ... 😕 

My "advice" is to _listen_ to the **Product Owner** who _rightly_ pointed out 
that serving CMS pages _through_ Phoenix adds an _unnecessary_ step 
to content publishing/updating which is using developer time in-effectively. 

> I _agreed_ with @sarahwelton that we don't _want_ to have a "bespoke" CMS solution (_with Phoenix "in front" of Wagtail_) that ends up requiring a "_specialised_" team of developers 
to maintain/update/extend it.
> _The **last** thing we (@dwyl) **want** is our clients/projects being **dependent** on us, 
that's why we **document** (and test) our work as much as possible and make the code accessible/beginner-friendly so that **any** team of developers can maintain/extend it_.

When I _proposed_ the initial architecture, please see:
https://github.com/LDMW/app/tree/e0c6d43d306071e82afdcec0682d07e49b29e5c6#project-overview
_**notice** how my original diagram shows the **content** being **served** from **Wagtail**_ (_through CloudFlare for speed_) ?
The idea was to build the "**peer-to-peer**" elements of user interaction in Phoenix, 
_not_ to serve the CMS content through Phoenix ... 

The _requirement_ was for "**peer-to-peer**" user interaction, i.e. users (_suffering with sleep-related mental health issues_) would be able to interact with and help _each_ other with some moderation but with the aim of helping each other find ways to overcome their sleep issues.

> Our idea was to have "Chat" functionality in the LDMW Web app which would allow users to communicate in real-time. _However_ this was _not_ meant to be built during the "Alpha" phase, rather it was to be _re-visited_ in "Beta". 
> Phoenix is _brilliant_ for peer-to-peer. It uses the Erlang VM which is what WhatsApp, WeChat and Facebook Messenger all use for low-latency, high reliability chat.

In light of the _change in requirements_ (_away from having a "**peer-to-peer**" application_) -
 which Kumar _confirmed_ on the call -  I ***agreed*** with Sarah that Phoenix is not required for running a CMS. The conclusion from the call is that LDMW is going to be a "_service_" which then directs users to other services, e.g: https://www.bigwhitewall.com

> _My **exact words** were: "It breaks my heart, but if we only need a CMS then we should consider removing Phoenix_". (_i.e. if we don't want peer-to-peer anymore then we probably don't need Phoenix_)

I _followed_ up with a **question**: What will _differentiate_ LDMW from other Content-based Websites?  

> _Why_ &/or _How_ would someone visit LDMW's website in the first place? 
is the content going to be _better_ (_more relevant to the target audience_) 
than any of the _existing_ content on the web? e.g:
> + Sleep Foundation https://sleepfoundation.org/insomnia/content/what-causes-insomnia
> + WebMD: http://www.webmd.com/sleep-disorders/guide/insomnia-symptoms-and-causes
> + Help Guide: https://www.helpguide.org/articles/sleep/insomnia-causes-and-cures.htm

> What is the **USP** that will give people a _reason_ to visit LDMW over another website/service? 
(_I thought "peer-to-peer" was the USP..._)

If we use an _existing_ CMS and simply add content, how long will it take to have _enough original_ content to start _ranking_ for the specific keywords in order to get organic traffic to the site?

To be clear, I'm not _against_ removing Phoenix (_especially if it's causing a "bottleneck" in content creation/publishing; that was **never** the intention_)
I just want it to be _recorded_ that it's not _my_ decision to remove Phoenix; 
I _still_ think that the original idea of having "**peer-to-peer**" mental health support is a "great feature" and for that Phoenix is _perfect_! (_nobody builds chat in Python/Django, it would be like digging a swimming pool with a teaspoon..._) 
I merely provided a "_high-level estimate_" for how long it would take to remove Phoenix from the _current_ LDMW setup,  and asked for the _decision_ to be recorded in an issue.

**Comment by reddog** [comment]
@nelsonic Misunderstanding or not (I'll try harder on that front), thanks very much for your replies - I'm certain I wouldn't have captured your input quite as precisely as that.

**Comment by shouston3** [comment]
We will from now on be working from issues on the cms repository: https://github.com/LDMW/cms

Closing this issue in favour of https://github.com/LDMW/cms/issues/50 to avoid duplicate issues
