### ISSUE TITLE
UI for Sprint 2 features

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#95]
- [x] 'Would you recommend this? 'Thumbs up - thumbs down
- [x] 'What else do you want help with?' input 
- [x] Resource Filters
- [x] Generic 'share' icon
- [x] Sleep Assessment button #77 
- [x] Password protection screen #85 
- [x] Crisis banner underneath 'what else do you want help with?' field #75 
- [x] Crisis page #75 
- [x] 'Success' message when a person submits their email in the alpha block at the bottom of the page #108 
- [x] Quote styling #111 
- [x] Expert/user review styling #110

**Comment by shouston3** [comment]
@Cleop has added some basic styling to the password protection screen (it's all ready and waiting for when you need it)

The page so far looks like this:

![screen shot 2017-05-04 at 20 12 58](https://cloud.githubusercontent.com/assets/15983736/25720824/3434e8fc-3106-11e7-85a4-f07af403374b.png)

**Comment by iteles** [comment]
@shouston3 Moved your comment into the relevant issue 👍
